# -*- coding: utf-8 -*-
"""Dilara Ünsal - HW#2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17hS2fzrk4IrlkXUSY_o4oZOtnTRJ9njR
"""

# Homework 2

#1
un = "namename"
pw = "pwpw"

username = input("Please enter username: ")
password = input("and password: ")

if un==username && pw == password:
  print("Login is successful")


#2
dic = {"1":"a", "2":"b", "username":"password"}
un = input("Please enter username: ")
pw = input("and password: ")
if (un:pw) == dic(username:password) :
  print("Login is successful")