# -*- coding: utf-8 -*-
"""Dilara Ünsal - HW#3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vAs3pts2k6cXTMXFnmYvBgedg799Y5mB
"""

# Homework 3

# öğrenci isimleri
a = input("Please enter first student's name: ")
b = input("Please enter second student's name: ")
c = input("Please enter third student's name: ")
d = input("Please enter forth student's name: ")
e = input("Please enter fifth student's name: ")

# notlar
midterm, project, final = []
for i in range(0,5):
  midterm[i] = int(input("Please enter midterm grades: "))

for i in range(0,5):
  project[i] = int(input("Please enter project grades: "))
  
for i in range(0,5):
  final[i] = int(input("Please enter final grades: "))

passingGrade = []
for i in range(0,5):
  passingGrade[i] = midterm[i] * (0.3) + project[i] * (0.3) + final[i] * (0.4)

notlar = {}
notlar["a"] = passingGrade[0]
notlar["b"] = passingGrade[1]
notlar["c"] = passingGrade[2]
notlar["d"] = passingGrade[3]
notlar["e"] = passingGrade[4]


# not sıralaması
passingGrade = passingGrade.sort()
passingGrade = passingGrade.reverse()